# Coords of btns the bot tries to press.
[lobby]
trophies_region_crop = [880, 160, 1000, 220] # not used anymore, doesnt matter
brawlers_btn = [90, 450] #c
select_btn = [180, 850] #c
brawl_stars_icon = [600, 300] # BRAWL STARS ICON WHEN BRAWL STARS CRASHES. SET MANUALLY
trophy_observer = [20, 90, 400, 105] #c
[template_matching]
# Regions which will be cropped and then template will be looked for
# Example: powerpoint region will crop out a region in which powerpoints are visible inside the shop
powerpoint = [1013, 11, 65, 65]
brawler_menu_task = [1463, 8, 70, 70]
close_popup = [1235, 70, 555, 278]  # test laterrrrrr
lobby_menu = [1871, 78, 74, 54]
brawl_pass_house = [1781, 10, 116, 80]
go_back_arrow = [49, 11, 77, 84]
star_drop = [450, 200, 600, 575]  # test later

